mouse click shortcut for view and escape key for summary
cs2103t/collate pull request #44
Opened 2016-12-09 15:00 UTC by riwu

Allows clicking on a row to view the contribution statistics of the author associated with the row.
Pressing the escape key will return to the summary.

2016-12-10 03:48 UTC, damithc commented
@sebastianquek any thoughts?

2016-12-10 11:38 UTC, sebastianquek requested changes
Overall, looks good! 👍 

Do take note of the formatting, I've followed the Java Coding Standards as mentioned in CS2103.

2016-12-10 11:38 UTC, sebastianquek commented on src/main/java/gui/MainApp.java
> +    	commandBarController = new CommandBarController(mainApp);
Whitespace formatting

2016-12-10 11:38 UTC, sebastianquek commented on src/main/java/gui/MainApp.java
> +        	addSummary(this);
Use 4 spaces to indent, not tabs

2016-12-10 11:38 UTC, sebastianquek commented on src/main/java/gui/MainApp.java
> +    	String authorName = selectedAuthor.nameProperty().get();
Whitespace formatting, this includes the several lines after this.

2016-12-10 11:38 UTC, sebastianquek commented on src/main/java/gui/SummaryController.java
> +	public SummaryController(MainApp mainApp, Collection<Author> inputSummaryData) {
Use 4 spaces

2016-12-10 11:38 UTC, sebastianquek commented on src/main/java/gui/SummaryController.java
> +        	mainApp.handleMouseClick(newValue);
Use 4 spaces

2016-12-10 12:15 UTC, riwu commented on src/main/java/gui/MainApp.java
> +    	commandBarController = new CommandBarController(mainApp);
What's whitespace formatting? Is it a different problem from tab indentation?

Also do you indent empty lines?

2016-12-10 12:19 UTC, sebastianquek commented on src/main/java/gui/MainApp.java
> +    	commandBarController = new CommandBarController(mainApp);
It's the same as tab indentation, use 4 spaces.
No, do not indent empty lines!

2016-12-10 12:45 UTC, riwu commented
Fixed the tab indentation with autoformatting, which removed a few pre-existing empty line indentation as well, let me know if I missed anything.
Do you want the commits to be squashed into one btw?

2016-12-10 12:55 UTC, sebastianquek commented on src/main/java/gui/SummaryController.java
> +                .addListener((observableValue, oldValue, newValue) -> {
Could you also indent this block to match the previous statement's dot separator?

2016-12-10 12:56 UTC, sebastianquek commented
@riwu Sure, you can squash the commits into one! Thanks!!

2016-12-11 00:54 UTC, sebastianquek approved these changes

2016-12-11 00:55 UTC, merged